### ISSUE TITLE
FR: Custom palettes

### ISSUE THREAD

**Issue by ilyagr** [slowli/term-transcript#60]
I would like to use themes like https://github.com/chriskempson/tomorrow-theme. While I could try adding them to the list of palettes term-transcript supports, perhaps the could also have a `--palette-file` (or `--config-file`) option?

We could borrow the format from Alacritty (though perhaps converted to TOML; Alacritty is also moving in that direction):

```yaml
colors:
    normal:
        black:   '#3c3836' # color0
        red:     '#b85651' # color1
        green:   '#8f9a52' # color2
        yellow:  '#c18f41' # color3
        blue:    '#68948a' # color4
        magenta: '#ab6c7d' # color5
        cyan:    '#72966c' # color6
        white:   '#a89984' # color7
    bright:
        black:   '#5a524c' # color8
        red:     '#b85651' # color9
        green:   '#a9b665' # color10
        yellow:  '#d8a657' # color11
        blue:    '#7daea3' # color12
        magenta: '#d3869b' # color13
        cyan:    '#89b482' # color14
        white:   '#ddc7a1' # color15
```

The TOML version would be

```toml
[colors.normal]
black = "..."
# ...
[colors.bright]
black = "..."
```

Alternatively, the palette could be specified via CSS, but I'm less familiar with how that would work.
